// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://llhcrusgtllrdiqdrhtd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxsaGNydXNndGxscmRpcWRyaHRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY1Njk0MzMsImV4cCI6MjA5MjE0NTQzM30.dWu3EOvSKgOzHle8keElhsKUprntLDE-gVTcBlm3N_s";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);